server:
  port: 8081

spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      dialect: dialect=org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${EC2_HOST}:3306/hypevoice
    username: ${EC2_USERNAME}
    password: ${EC2_PASSWORD}


  #application-secret.yml
  profiles:
    include: secret
